name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: nokotech/actions
      uses: nokotech/actions/release@master
    - name: ls
      run: |
        ls -la 
