name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: nokotech/actions
      uses: nokotech/actions/release@release
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        owner: TakenokoTech
        repo: sample-actions
        dir: ./
        file: README.md
        content-type: text/plain
    - name: git push release
      run: |
        git remote set-url origin https://TakenokoTech:${{ secrets.GITHUB_TOKEN }}@github.com/TakenokoTech/sample-actions.git
        git checkout -b release
        git push --force-with-lease origin release
